In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [3]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_Asia"

page = requests.get(url)
soup = BeautifulSoup(page.text,'html')

In [24]:
table = soup.find('table',class_ = "wikitable sortable")

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_Asia"

page = requests.get(url)
soup = BeautifulSoup(page.text,'html')
table = soup.find('table',class_ = "wikitable sortable")
word_titles= table.find_all('th')
word_titles_table = [title.text.strip() for title in word_titles]
df=pd.DataFrame(columns = word_titles_table[:8])
for row in column_data[3:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    print(individual_row_data)
    # length = len(df)
    # df.loc[length] = individual_row_data

In [25]:
# soup.find_all('table')[1]

In [42]:
print(table)

<table class="wikitable sortable" style="text-align:left;">
<tbody><tr>
<th rowspan="2" scope="col">Rank
</th>
<th rowspan="2" scope="col">Name
</th>
<th rowspan="2" scope="col">Industry
</th>
<th scope="col">Revenue
</th>
<th scope="col">Profit
</th>
<th rowspan="2" scope="col">Employees
</th>
<th rowspan="2" scope="col">Headquarters
</th></tr>
<tr>
<th colspan="2" scope="col"><small>USD millions</small>
</th></tr>
<tr>
<th scope="row">1
</th>
<td><a href="/wiki/Saudi_Aramco" title="Saudi Aramco">Saudi Aramco</a>
</td>
<td><a class="mw-redirect" href="/wiki/Oil_and_gas" title="Oil and gas">Oil and gas</a>
</td>
<td style="text-align:center;">$603,651
</td>
<td style="text-align:center;">$159,069
</td>
<td style="text-align:center;">70,496
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Saudi_Arabia" title="Saudi Arabia"><img alt="Saudi Arabia" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/23px-Flag_of_Saudi_Arabia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/35px-Flag_of_Saudi_Arabia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/45px-Flag_of_Saudi_Arabia.svg.png 2x" width="23"/></a></span></span> Saudi Arabia
</td></tr>
<tr>
<th scope="row">2
</th>
<td><a href="/wiki/State_Grid_Corporation_of_China" title="State Grid Corporation of China">State Grid Corporation of China</a>
</td>
<td><a href="/wiki/Electric_utility" title="Electric utility">Electricity</a>
</td>
<td style="text-align:center;">$530,009
</td>
<td style="text-align:center;">$8,192
</td>
<td style="text-align:center;">870,287
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">3
</th>
<td><a href="/wiki/China_National_Petroleum_Corporation" title="China National Petroleum Corporation">China National Petroleum Corporation</a>
</td>
<td><a class="mw-redirect" href="/wiki/Oil_and_gas" title="Oil and gas">Oil and gas</a>
</td>
<td style="text-align:center;">$483,019
</td>
<td style="text-align:center;">$21,080
</td>
<td style="text-align:center;">1,087,049
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">4
</th>
<td><a class="mw-redirect" href="/wiki/China_Petrochemical_Corporation" title="China Petrochemical Corporation">China Petrochemical Corporation</a>
</td>
<td><a class="mw-redirect" href="/wiki/Oil_and_gas" title="Oil and gas">Oil and gas</a>
</td>
<td style="text-align:center;">$471,154
</td>
<td style="text-align:center;">$9,657
</td>
<td style="text-align:center;">527,487
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">5
</th>
<td><a href="/wiki/Trafigura" title="Trafigura">Trafigura</a>
</td>
<td><a href="/wiki/Commodity_market" title="Commodity market">Commodities</a>
</td>
<td style="text-align:center;">$318,476
</td>
<td style="text-align:center;">$6,994
</td>
<td style="text-align:center;">12,347
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Singapore" title="Singapore"><img alt="Singapore" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/35px-Flag_of_Singapore.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/45px-Flag_of_Singapore.svg.png 2x" width="23"/></a></span></span> Singapore
</td></tr>
<tr>
<th scope="row">6
</th>
<td><a href="/wiki/China_State_Construction_Engineering" title="China State Construction Engineering">China State Construction Engineering</a>
</td>
<td><a href="/wiki/Construction" title="Construction">Construction</a>
</td>
<td style="text-align:center;">$305,885
</td>
<td style="text-align:center;">$4,234
</td>
<td style="text-align:center;">382,492
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">7
</th>
<td><a href="/wiki/Toyota" title="Toyota">Toyota</a>
</td>
<td><a class="mw-redirect" href="/wiki/Automotive" title="Automotive">Automotive</a>
</td>
<td style="text-align:center;">$274,491
</td>
<td style="text-align:center;">$18,110
</td>
<td style="text-align:center;">375,235
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Japan" title="Japan"><img alt="Japan" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/23px-Flag_of_Japan.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/35px-Flag_of_Japan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/45px-Flag_of_Japan.svg.png 2x" width="23"/></a></span></span> Japan
</td></tr>
<tr>
<th scope="row">8
</th>
<td><a href="/wiki/Samsung_Electronics" title="Samsung Electronics">Samsung Electronics</a>
</td>
<td><a href="/wiki/Electronics" title="Electronics">Electronics</a>
</td>
<td style="text-align:center;">$234,129
</td>
<td style="text-align:center;">$42,398
</td>
<td style="text-align:center;">270,372
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/South_Korea" title="South Korea"><img alt="South Korea" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/35px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/45px-Flag_of_South_Korea.svg.png 2x" width="23"/></a></span></span> South Korea
</td></tr>
<tr>
<th scope="row">9
</th>
<td><a href="/wiki/Foxconn" title="Foxconn">Foxconn</a>
</td>
<td><a href="/wiki/Electronics" title="Electronics">Electronics</a>
</td>
<td style="text-align:center;">$222,535
</td>
<td style="text-align:center;">$4,751
</td>
<td style="text-align:center;">767,062
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Taiwan" title="Taiwan"><img alt="Taiwan" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/35px-Flag_of_the_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/45px-Flag_of_the_Republic_of_China.svg.png 2x" width="23"/></a></span></span> Taiwan
</td></tr>
<tr>
<th scope="row">10
</th>
<td><a href="/wiki/Industrial_and_Commercial_Bank_of_China" title="Industrial and Commercial Bank of China">Industrial and Commercial Bank of China</a>
</td>
<td><a href="/wiki/Financial_services" title="Financial services">Financials</a>
</td>
<td style="text-align:center;">$214,766
</td>
<td style="text-align:center;">$53,589
</td>
<td style="text-align:center;">427,587
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">11
</th>
<td><a href="/wiki/China_Construction_Bank" title="China Construction Bank">China Construction Bank</a>
</td>
<td><a href="/wiki/Financial_services" title="Financial services">Financials</a>
</td>
<td style="text-align:center;">$202,753
</td>
<td style="text-align:center;">$48,145
</td>
<td style="text-align:center;">376,682
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">12
</th>
<td><a href="/wiki/Agricultural_Bank_of_China" title="Agricultural Bank of China">Agricultural Bank of China</a>
</td>
<td><a href="/wiki/Financial_services" title="Financial services">Financials</a>
</td>
<td style="text-align:center;">$187,061
</td>
<td style="text-align:center;">$38,524
</td>
<td style="text-align:center;">452,258
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">13
</th>
<td><a href="/wiki/Ping_An_Insurance" title="Ping An Insurance">Ping An Insurance</a>
</td>
<td><a href="/wiki/Financial_services" title="Financial services">Financials</a>
</td>
<td style="text-align:center;">$181,566
</td>
<td style="text-align:center;">$12,454
</td>
<td style="text-align:center;">344,223
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th>14
</th>
<td><a href="/wiki/Sinochem" title="Sinochem">Sinochem</a>
</td>
<td><a href="/wiki/Chemical_industry" title="Chemical industry">Chemicals</a>
</td>
<td style="text-align:center;">$173,834
</td>
<td style="text-align:center;">–$1
</td>
<td style="text-align:center;">220,760
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">15
</th>
<td><a href="/wiki/China_Railway_Engineering_Corporation" title="China Railway Engineering Corporation">China Railway Engineering Corporation</a>
</td>
<td><a href="/wiki/Construction" title="Construction">Construction</a>
</td>
<td style="text-align:center;">$171,669
</td>
<td style="text-align:center;">$2,035
</td>
<td style="text-align:center;">314,792
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">16
</th>
<td><a href="/wiki/China_National_Offshore_Oil_Corporation" title="China National Offshore Oil Corporation">China National Offshore Oil Corporation</a>
</td>
<td><a href="/wiki/Fossil_fuel" title="Fossil fuel">Oil and gas</a>
</td>
<td style="text-align:center;">$164,762
</td>
<td style="text-align:center;">$16,988
</td>
<td style="text-align:center;">81,775
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">17
</th>
<td><a href="/wiki/China_Railway_Construction_Corporation" title="China Railway Construction Corporation">China Railway Construction Corporation</a>
</td>
<td><a href="/wiki/Construction" title="Construction">Construction</a>
</td>
<td style="text-align:center;">$163,037
</td>
<td style="text-align:center;">$1,800
</td>
<td style="text-align:center;">342,098
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th scope="row">18
</th>
<td><a href="/wiki/Baowu" title="Baowu">Baowu</a>
</td>
<td><a href="/wiki/Steel" title="Steel">Steel</a>
</td>
<td style="text-align:center;">$161,698
</td>
<td style="text-align:center;">$2,493
</td>
<td style="text-align:center;">245,675
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></a></span></span> China
</td></tr>
<tr>
<th>19
</th>
<td><a class="mw-redirect" href="/wiki/Mitsubishi_Group" title="Mitsubishi Group">Mitsubishi Group</a>
</td>

In [60]:
word_titles= table.find_all('th')

In [61]:
word_titles

[<th rowspan="2" scope="col">Rank
 </th>,
 <th rowspan="2" scope="col">Name
 </th>,
 <th rowspan="2" scope="col">Industry
 </th>,
 <th scope="col">Revenue
 </th>,
 <th scope="col">Profit
 </th>,
 <th rowspan="2" scope="col">Employees
 </th>,
 <th rowspan="2" scope="col">Headquarters
 </th>,
 <th colspan="2" scope="col"><small>USD millions</small>
 </th>,
 <th scope="row">1
 </th>,
 <th scope="row">2
 </th>,
 <th scope="row">3
 </th>,
 <th scope="row">4
 </th>,
 <th scope="row">5
 </th>,
 <th scope="row">6
 </th>,
 <th scope="row">7
 </th>,
 <th scope="row">8
 </th>,
 <th scope="row">9
 </th>,
 <th scope="row">10
 </th>,
 <th scope="row">11
 </th>,
 <th scope="row">12
 </th>,
 <th scope="row">13
 </th>,
 <th>14
 </th>,
 <th scope="row">15
 </th>,
 <th scope="row">16
 </th>,
 <th scope="row">17
 </th>,
 <th scope="row">18
 </th>,
 <th>19
 </th>,
 <th>20
 </th>,
 <th>21
 </th>,
 <th>22
 </th>,
 <th>23
 </th>,
 <th>24
 </th>,
 <th>25
 </th>,
 <th>26
 </th>,
 <th>27
 </th>,
 <th>28
 </th>,
 <th>29
 </th>,
 <th>30
 </th>]

In [62]:
word_titles_table = [title.text.strip() for title in word_titles]

print(word_titles_table)

['Rank', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees', 'Headquarters', 'USD millions', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']

In [63]:
word_titles_table

['Rank',
 'Name',
 'Industry',
 'Revenue',
 'Profit',
 'Employees',
 'Headquarters',
 'USD millions',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30']

In [73]:
import pandas as pd
df=pd.DataFrame(columns = word_titles_table[:7])
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue, Profit, Employees, Headquarters]
Index: []

In [74]:
column_data = table.find_all('tr')

In [76]:
for row in column_data[2:]:
    row_data = row.find_all(['th','td'])
    individual_row_data = [data.text.strip() for data in row_data]
    # print(individual_row_data)
    length = len(df)
    df.loc[length] = individual_row_data

In [77]:
df

,Rank,Name,Industry,Revenue,Profit,Employees,Headquarters
0,1,Saudi Aramco,Oil and gas,"$603,651","$159,069","70,496",Saudi Arabia
1,2,State Grid Corporation of China,Electricity,"$530,009","$8,192","870,287",China
2,3,China National Petroleum Corporation,Oil and gas,"$483,019","$21,080","1,087,049",China
3,4,China Petrochemical Corporation,Oil and gas,"$471,154","$9,657","527,487",China
4,5,Trafigura,Commodities,"$318,476","$6,994","12,347",Singapore
5,6,China State Construction Engineering,Construction,"$305,885","$4,234","382,492",China
6,7,Toyota,Automotive,"$274,491","$18,110","375,235",Japan
7,8,Samsung Electronics,Electronics,"$234,129","$42,398","270,372",South Korea
8,9,Foxconn,Electronics,"$222,535","$4,751","767,062",Taiwan
9,10,Industrial and Commercial Bank of China,Financials,"$214,766","$53,589","427,587",China
10,11,China Construction Bank,Financials,"$202,753","$48,145","376,682",China
11,12,Agricultural Bank of China,Financials,"$187,061","$38,524","452,258",China
12,13,Ping An Insurance,Financials,"$181,566","$12,454","344,223",China
13,14,Sinochem,Chemicals,"$173,834",–$1,"220,760",China
14,15,China Railway Engineering Corporation,Construction,"$171,669","$2,035","314,792",China
15,16,China National Offshore Oil Corporation,Oil and gas,"$164,762","$16,988","81,775",China
16,17,China Railway Construction Corporation,Construction,"$163,037","$1,800","342,098",China
17,18,Baowu,Steel,"$161,698","$2,493","245,675",China
18,19,Mitsubishi Group,Conglomerate,"$159,371","$8,723","79,706",Japan
19,20,JD.com,E-commerce,"$155,533","$1,543","450,679",China
20,21,China Life Insurance Company,Insurance,"$151,487","$6,859","180,619",China
21,22,China Mobile,Telecommunications,"$139,597","$14,718","452,202",China
22,23,China Minmetals,Mining,"$133,541",$877,"183,298",China
23,24,Alibaba Group,Technology,"$129,059","$10,625","235,216",China
24,25,Xiamen C & D,Logistics,"$125,971",$454,"40,959",China
25,26,Honda Motor,Automotive,"$124,912","$4,813","197,039",Japan
26,27,Shandong Energy,Mining,"$124,089",$33,"232,841",China
27,28,China Resources,Conglomerate,"$121,643","$4,662","379,944",China
28,29,China Energy Investment,Energy,"$121,427","$5,699","310,753",China
29,30,China Southern Power Grid,Electricity,"$113,674","$1,516","271,202",China
30,1,Saudi Aramco,Oil and gas,"$603,651","$159,069","70,496",Saudi Arabia
31,2,State Grid Corporation of China,Electricity,"$530,009","$8,192","870,287",China
32,3,China National Petroleum Corporation,Oil and gas,"$483,019","$21,080","1,087,049",China
33,4,China Petrochemical Corporation,Oil and gas,"$471,154","$9,657","527,487",China
34,5,Trafigura,Commodities,"$318,476","$6,994","12,347",Singapore
35,6,China State Construction Engineering,Construction,"$305,885","$4,234","382,492",China
36,7,Toyota,Automotive,"$274,491","$18,110","375,235",Japan
37,8,Samsung Electronics,Electronics,"$234,129","$42,398","270,372",South Korea
38,9,Foxconn,Electronics,"$222,535","$4,751","767,062",Taiwan
39,10,Industrial and Commercial Bank of China,Financials,"$214,766","$53,589","427,587",China
40,11,China Construction Bank,Financials,"$202,753","$48,145","376,682",China
41,12,Agricultural Bank of China,Financials,"$187,061","$38,524","452,258",China
42,13,Ping An Insurance,Financials,"$181,566","$12,454","344,223",China
43,14,Sinochem,Chemicals,"$173,834",–$1,"220,760",China
44,15,China Railway Engineering Corporation,Construction,"$171,669","$2,035","314,792",China
45,16,China National Offshore Oil Corporation,Oil and gas,"$164,762","$16,988","81,775",China
46,17,China Railway Construction Corporation,Construction,"$163,037","$1,800","342,098",China
47,18,Baowu,Steel,"$161,698","$2,493","245,675",China
48,19,Mitsubishi Group,Conglomerate,"$159,371","$8,723","79,706",Japan
49,20,JD.com,E-commerce,"$155,533","$1,543","450,679",China
50,21,China Life Insurance Company,Insurance,"$151,487","$6,859","180,619",China
51,22,China Mobile,Telecommunications,"$139,597","$14,718","452,202",China
52,23,China Minmetals,Mining,"$133,541",$877,"183,298",China
53,24,Alibaba Group,Technology,"$129,059","$10,625","235,216",China
54,25,Xiamen C & D,Logistics,"$125,971",$454,"40,959",China
55,26,Honda Motor,Automotive,"$124,912","$4,813","197,039",Japan
56,27,Shandong Energy,Mining,"$124,089",$33,"232,841",China
57,28,China Resources,Conglomerate,"$121,643","$4,662","379,944",China
58,29,China Energy Investment,Energy,"$121,427","$5,699","310,753",China
59,30,China Southern Power Grid,Electricity,"$113,674","$1,516","271,202",China

In [78]:
df.isnull().sum()

Rank            0
Name            0
Industry        0
Revenue         0
Profit          0
Employees       0
Headquarters    0
dtype: int64

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          60 non-null     object
 1   Name          60 non-null     object
 2   Industry      60 non-null     object
 3   Revenue       60 non-null     object
 4   Profit        60 non-null     object
 5   Employees     60 non-null     object
 6   Headquarters  60 non-null     object
dtypes: object(7)
memory usage: 3.8+ KB

In [80]:
df.describe()

,Rank,Name,Industry,Revenue,Profit,Employees,Headquarters
count,60,60,60,60,60,60,60
unique,30,30,17,30,30,30,6
top,1,Saudi Aramco,Oil and gas,"$603,651","$159,069","70,496",China
freq,2,2,8,2,2,2,46

In [85]:
df['Headquarters'].value_counts()

China           46
Japan            6
Saudi Arabia     2
Singapore        2
South Korea      2
Taiwan           2
Name: Headquarters, dtype: int64